[project]
name = "learning-ai"
version = "0.1.0"
description = "Monorepo for AI learning journey"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain[openai]>=0.3.26",
    "pymongo[ocsp]>=4.13.2",
]
